### ISSUE TITLE
You could add the scheme data of mongoDB?

### ISSUE THREAD

**Issue by juanter** [AgoraBinaria/app-base#25]
i'm having troubles with the initial data of MongoDB, could you add a file explaining this, or tell where i can find it?, becouse not work for me, only i get the login

I had created the collections:
bookings, events, mails, organizations, payments, users, credentials(I don't undertand why duplicate password in this collection).

and added 
users:
```
{
    "_id" : ObjectId("594b7e4b6e335e7adba40722"),
    "name" : "god user",
    "email" : "admin@agorabinaria.com",
    "password" : "AGoodGodPassword:-)",
    "roles" : [ 
        "admin", 
        "client", 
        "god", 
        "organizer", 
        "public", 
        "usher"
    ],
    "status" : "active"
}
```
credentials:
```
{
    "_id" : ObjectId("594b80216e335e7adba407f2"),
    "userId" : "594b7e4b6e335e7adba40722",
    "password" : "AGoodGodPassword:-)"
}
```

**Comment by AlbertoBasalo** [comment]
The mongo schema will be at the *.models.ts files on the server side.

The password field should only be at credentials collection. If it is in users is an error.

**Comment by juanter** [comment]
Ok, but the readme.md in the credentials folder is a little confuse, and say:
- Creación manual en base de datos
```json
{
    "name" : "god user",
    "email" : "admin@agorabinaria.com",
    "password" : "AGoodGodPassword:-)",
    "status" : "ACTIVE"
}
```
[https://github.com/AgoraBinaria/app-base/blob/master/server/src/app/routes/credentials/readme.md](url)

I understand that y only have to create a user god an his credentials and the collections:
bookings, events, mails, organizations, payments, users, credentials

But it don't work for me. I only get the server accept the login, and in the next page i can not do anything.

**Comment by AlbertoBasalo** [comment]
We haven't implemented any functionalities at the moment.
Only god creation and shared components.

**Comment by juanter** [comment]
ok, thanks.
I asked becouse in the course of "Angular y Observables", you showed us the features of this application and you told me that it was an example to learn just good practices for the development that I have to develop.

**Comment by AlbertoBasalo** [comment]
Thanks for your comments. You are wellcome. 
This is a work in progress. Please stay tuned.
